// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/blog.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$2 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/AIBuildersHome.tsx";
import * as $$$$$$1 from "./sections/AuthLogin.tsx";
import * as $$$$$$2 from "./sections/AuthSignup.tsx";
import * as $$$$$$3 from "./sections/BlogPost.tsx";
import * as $$$$$$4 from "./sections/BlogPosts.tsx";
import * as $$$$$$5 from "./sections/BuilderDetail.tsx";
import * as $$$$$$6 from "./sections/BuilderProfilePage.tsx";
import * as $$$$$$7 from "./sections/BuildersGrid.tsx";
import * as $$$$$$8 from "./sections/BuildersPage.tsx";
import * as $$$$$$9 from "./sections/Faq.tsx";
import * as $$$$$$10 from "./sections/Footer.tsx";
import * as $$$$$$11 from "./sections/Header.tsx";
import * as $$$$$$12 from "./sections/Hero.tsx";
import * as $$$$$$13 from "./sections/HeroBounties.tsx";
import * as $$$$$$14 from "./sections/ImageWithParagraph.tsx";
import * as $$$$$$15 from "./sections/Logos.tsx";
import * as $$$$$$16 from "./sections/MainPost.tsx";
import * as $$$$$$17 from "./sections/Testimonials.tsx";
import * as $$$$$$18 from "./sections/Theme/Theme.tsx";

const manifest = {
  "sections": {
    "site/sections/AIBuildersHome.tsx": $$$$$$0,
    "site/sections/AuthLogin.tsx": $$$$$$1,
    "site/sections/AuthSignup.tsx": $$$$$$2,
    "site/sections/BlogPost.tsx": $$$$$$3,
    "site/sections/BlogPosts.tsx": $$$$$$4,
    "site/sections/BuilderDetail.tsx": $$$$$$5,
    "site/sections/BuilderProfilePage.tsx": $$$$$$6,
    "site/sections/BuildersGrid.tsx": $$$$$$7,
    "site/sections/BuildersPage.tsx": $$$$$$8,
    "site/sections/Faq.tsx": $$$$$$9,
    "site/sections/Footer.tsx": $$$$$$10,
    "site/sections/Header.tsx": $$$$$$11,
    "site/sections/Hero.tsx": $$$$$$12,
    "site/sections/HeroBounties.tsx": $$$$$$13,
    "site/sections/ImageWithParagraph.tsx": $$$$$$14,
    "site/sections/Logos.tsx": $$$$$$15,
    "site/sections/MainPost.tsx": $$$$$$16,
    "site/sections/Testimonials.tsx": $$$$$$17,
    "site/sections/Theme/Theme.tsx": $$$$$$18,
  },
  "apps": {
    "site/apps/deco/blog.ts": $$$$$$$$$$$0,
    "site/apps/deco/htmx.ts": $$$$$$$$$$$1,
    "site/apps/site.ts": $$$$$$$$$$$2,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
